### ISSUE TITLE
is this project still relevant for F33?

### ISSUE THREAD

**Issue by makarov-roman** [silenc3r/fedora-better-fonts#23]

**Comment by brndd** [comment]
It looks like all the fonts except for ubuntu-fonts are included in Fedora repos since 33. This was giving me an error when updating because the same package was provided by multiple sources.

**Comment by silenc3r** [comment]
This should be fixed by now. If not, could you please tell me which fonts cause problems?

**Comment by brndd** [comment]
I'll get back to you if the issue returns. The KDE updater widget was giving me the error, but manually updating with `dnf update` updated all the font packages fine so maybe that was what's necessary for getting rid of the error.

I did reinstall the COPR repo and its contents (`fontconfig-font-replacements`) while troubleshooting and I swear the font on Github looks slightly different now, though... Oh well.

**Comment by brndd** [comment]
Turns out I wasn't just imagining things. Without the old [enhanced defaults](https://github.com/silenc3r/fedora-better-fonts/blob/bff40f5c1191af35685f474602816befd1608b3a/fontconfig-enhanced-defaults/19-enhanced-defaults.conf) file, fonts look really ugly on my system, at least in Firefox. I stuck the contents of that file into `~/.fonts.conf` for now and things are fine, but are the system defaults really supposed to still be this ugly?

Comparisons below, though it's difficult to see the difference in screenshots for some reason. Try opening them in tabs and flashing back and forth. The "before" one feels like it doesn't have proper antialiasing or something.

## After

![2020-11-01_180238](https://user-images.githubusercontent.com/5822375/97807999-a417c900-1c6c-11eb-8d2e-3615d21f97d7.png)

## Before

![2020-11-01_180158](https://user-images.githubusercontent.com/5822375/97807997-a2e69c00-1c6c-11eb-912b-4c0c7864a699.png)

**Comment by silenc3r** [comment]
It's a matter of taste. 

Practically, the only thing`fontconfig-enhanced-defaults` did was to change antialiasing from grayscale to rgb. Other options were just replicating the defaults.

RGB antialiasing has it's warts which are especially evident with small white letters on black background and/or when using Night Light. Some people notice them and can't stand them, others don't. It's the kind of thing that once seen cannot be unseen ;).

Nonetheless, I was maybe too eager with removing `fontconfig-enhanced-defaults`. I'll reconsider enabling it again.

(And yes, github font is slightly different (Arimo instead of Nimbus Sans). Numbers next to Issues and Pull Requests now align with the text. That thing was giving me serious OCD).

**Comment by brndd** [comment]
Ah, I see. I suppose I'm just used to RGB antialiasing from Windows. Thanks for the explanation, and for maintaining this thing.

**Comment by silenc3r** [comment]
I've re-enabled `fontconfig-enhanced-defaults`.

**Comment by makarov-roman** [comment]
Thanks. I'll close the pr then.
