### ISSUE TITLE
Would you please add support for the branched FC27?

### ISSUE THREAD

**Issue by wilbert-vb** [silenc3r/fedora-better-fonts#3]
FC27 is branched and can be enabled in copr, would you please support this (beta-)release?

It looks like there is a setting that automatically creates repos for new branches: Settings / Other Options / Follow Fedora branching.

Thank you very much.

**Comment by silenc3r** [comment]
Done. I've enabled automated branching too.

**Comment by jonas2515** [comment]
It seems like the automatic builds failed: https://copr.fedorainfracloud.org/coprs/dawid/better_fonts/builds/

**Comment by silenc3r** [comment]
Yes, I tried rebuilding packages today and I'm always getting the same error saying that temp dir couldn't be created because it already exists. I assume that building from git repo is currently broken on copr and based on my experiences with using this service, it won't be fixed any time soon.

I will build all packages on my machine and upload srpms manually. I hope that will work.

**Comment by wilbert-vb** [comment]
I had to download the sources and build local, it turned out that some links in the download shell scripts are broken.
I have srpms available, if that would help.

**Comment by silenc3r** [comment]
Thanks, but I have to update this repo anyway. I've procrastinated too long with it. Hopefully I will do that tomorrow when I get access to faster internet connection so I can test things under Fedora 27.

**Comment by silenc3r** [comment]
COPR repo mysteriously vanished overnight but I have already recreated it and built all packages. It should be working on Fedora 27 now.
