### ISSUE TITLE
Breaks colored emoji in Gnome 3.26?

### ISSUE THREAD

**Issue by goncalossilva** [silenc3r/fedora-better-fonts#6]
Just updated to Fedora 27 and hit a weird issue: installing a colored emoji font (tried both Noto and EmojiOne) would result in Characters displaying blank emojis.

After some back and forth, `sudo dnf remove fontconfig-enhanced-defaults fontconfig-font-replacements`  fixed it.

**Comment by makruiten** [comment]
Do you some application installed to test emojis in Gnome notifications? I'm using Telegram Desktop with native notifications enabled in the settings. I remember that emojis didn't work after installing `fontconfig-enhanced-defaults` and `fontconfig-font-replacements`, but I made some changes since then and now they do work again. If you could confirm that emojis don't appear in Gnome notifications I might be able to help you fix them.

**Comment by makruiten** [comment]
What might just be enough is editing `/etc/fonts/conf.d/52-latin-free.conf` to include `<family>emoji</family>` as the second option for serif and non-serif. This should default to Noto Color Emoji (at least it does on my system). The relevant part:

```
  <!-- ## serif ## -->
  <alias>
    <family>serif</family>
    <prefer>
      <family>Noto Serif</family>
      <family>emoji</family>
      <family>DejaVu Serif</family>
      <family>Tinos</family>
      <family>Liberation Serif</family>
      <family>Nimbus Roman</family>
    </prefer>
  </alias>
  <!-- ## sans-serif ## -->
  <alias>
    <family>sans-serif</family>
    <prefer>
      <family>Noto Sans</family>
      <family>emoji</family>
      <family>Arimo</family>
      <family>Liberation Sans</family>
      <family>DejaVu Sans</family>
      <family>Nimbus Sans</family>
      <family>Open Sans</family>
    </prefer>
  </alias>
```

**Comment by goncalossilva** [comment]
Thanks! Unfortunately, no dice. I still see no emojis in Gnome itself (tried the Characters app and GPaste's gnome shell extension), just blank space.

What's interesting is that I see all colored emojis in the page you linked _when I have this installed_. When I don't, they're all black and white.

So, the current status is:
* With this installed, I see no color emojis (just blank space) in Gnome apps, colored emojis [here](http://www.fileformat.info/info/emoji/browsertest.htm).
* With this uninstalled, I see color emojis in Gnome apps, black and white emojis [here](http://www.fileformat.info/info/emoji/browsertest.htm).

Very unsure what's going on...

**Comment by makruiten** [comment]
What happens if you remove `fontconfig-enhanced-defaults`? Because I did those enhancements myself, so that might be it. Maybe it’s the setting for bitmap fonts.

**Comment by goncalossilva** [comment]
Yeah, removing `fontconfig-enhanced-defaults` brings back emojis in Gnome apps :smile:

**Comment by makruiten** [comment]
Nice. What you're missing now is proper cleartype-like rgb antialiasing. It's either disabled, or you should see obvious color fringing around text edges. The easiest way to enable it again is to install `fontconfig-enhanced-defaults` again and edit `/etc/fonts/conf.d/10-enhanced-defaults.conf` by removing this part:

```
<edit mode="assign" name="embeddedbitmap">
            <bool>false</bool>
</edit>
```

This is not what I did, but that would require creating multiple files and symbolic links, so this is easier for now. I think you can do `ln -s /usr/share/fontconfig/conf.avail/70-no-bitmaps.conf /etc/fonts/conf.d/` to replace the missing part without losing emoji support but it's not strictly necessary. To undo, simply run `rm /etc/fonts/conf.d/70-no-bitmaps.conf`. Fedora does this per font in `25-no-bitmap-fedora.conf` instead of for all fonts as `70-no-bitmaps.conf` does.

**Comment by goncalossilva** [comment]
Thanks @makruiten! That works. I also symlinked `70-no-bitmaps.conf`, though I am unsure how this affects the end result. Chrome still uses black & white emojis, but that was the case before.

**Comment by silenc3r** [comment]
I have removed ```10-enhanced-defaults.conf``` file from ```fontconfig-enhanced-defaults``` package and replaced it with symlinks to ```10-sub-pixel-rgb.conf```, ```11-lcdfilter-default.conf``` and ```70-no-bitmaps.conf```. It's a bit hacky (I'm providing symlinks to files from ```fontconfig``` package) but it seems to work.

Could you please test new package to see if it fixes your problem?

**Comment by goncalossilva** [comment]
Thanks @silenc3r. Reverted all my changes to try it out and I can confirm everything is working well in the latest version.
