### ISSUE TITLE
Incorrect symbols in SymbolNeu

### ISSUE THREAD

**Issue by tsoernes** [silenc3r/fedora-better-fonts#8]
I have attached a PDF. When opening it in the browser, math equations are correct. When opening it in Okular (PDF viewer), some symbols are incorrect. Okular says that 'google-croscore/SymbolNeu.ttf' is used for 'Symbol'.

Example 1, The sum sign is displayed as a dot. Page 2
[El-Alfy2001 Model-based Q-learning for wireless channel alloc.pdf](https://github.com/silenc3r/fedora-better-fonts/files/1885296/El-Alfy2001.Model-based.Q-learning.for.wireless.channel.alloc.pdf)

Example 2, Pi is displayed as not-eq. Page 135
[Wong2003 Thesis.pdf](https://github.com/silenc3r/fedora-better-fonts/files/1885312/Wong2003.Thesis.pdf)

**Comment by silenc3r** [comment]
I can confirm the issue, but it isn't caused by packages from this repo. I guess it's problem with poppler PDF rendering library. Removing SymbolNeu font fixes the issues you mentioned but causes others, e.g. curly brackets from document 1 page 3 are displayed as set of empty rectangles.

I don't think I can do anything to fix it.

**Comment by tsoernes** [comment]
Thanks for having a look. Reported it here. https://bugs.freedesktop.org/show_bug.cgi?id=105991

**Comment by tsoernes** [comment]
@silenc3r would you take a look at their response above.

**Comment by silenc3r** [comment]
StandardSymbolsPS is default font for displaying symbols on Fedora. The problem is that it doesn't display all characters correctly either for some reason. It does work as intended on Ubuntu though.

SymbolNeu seems to be problematic, as reported here: https://bugzilla.redhat.com/show_bug.cgi?id=923346

I will probably replace SymbolNeu with either Symbola or Open Symbol as they both seem to display all symbols correctly (at least the ones from your PDFs.)

**Comment by silenc3r** [comment]
I have submitted changes to copr repo. Please update your ```fontconfig-font-replacements``` and see if everything works fine for you.

**Comment by tsoernes** [comment]
Seems to work fine. Thank you very much.
